aws_profile: "trade-feed-etl-dev-profile"
db_instance_identifier: "dev-trade-feed-db"
db_name: "trade_feed_db"
db_user: "trade_feed_db_user"
db_password: "trade_feed_db_password_1!"
db_instance_class: "db.t2.micro"
db_engine: "postgres"
db_allocated_storage: 20
db_subnet_group_name: "your-subnet-group"
vpc_security_group_ids: ["your-security-group-id"]
master_username: trade_feed_db_user
master_user_password: trade_feed_db_master_user_password
allocated_storage: 20
