---
- name: Generate test data for PostgreSQL
  hosts: localhost
  gather_facts: no

  vars:
    json_file_path: "{{ lookup('env', 'HOME') }}/trade-feed-etl-health-checker_{{ aws_region }}_{{ environment }}.json"
    aws_credentials: "{{ lookup('file', json_file_path) | from_json }}"

  tasks:
    - name: Generate test data
      postgresql_db:
        name: "trade_feed_db"
        login_user: "{{ aws_credentials.db_master_username }}"
        login_password: "{{ aws_credentials.db_master_password }}"
        state: present

    - name: Insert test data into trades_data_ingestion_log table
      postgresql_query:
        db: "trade_feed_db"
        login_user: "{{ aws_credentials.db_master_username }}"
        login_password: "{{ aws_credentials.db_master_password }}"
        query: |
          INSERT INTO trades_data_ingestion_log (account_id, created, id, location)
          VALUES (generate_series(1, 1000), now(), uuid_generate_v4(), 's3://bucket-name/trades');
