---
- name: Set up PostgreSQL database in AWS
  hosts: localhost
  gather_facts: no

  vars:
    json_file_path: "{{ lookup('env', 'HOME') }}/trade-feed-etl-health-checker_{{ aws_region }}_{{ environment }}.json"
    aws_credentials: "{{ lookup('file', json_file_path) | from_json }}"

  tasks:
    - name: Create RDS PostgreSQL instance
      rds:
        command: create
        id: "{{ environment }}-rds-instance"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_credentials.aws_access_key_id }}"
        aws_secret_key: "{{ aws_credentials.aws_secret_access_key }}"
        db_instance_class: db.t2.micro
        engine: postgres
        allocated_storage: 20
        master_username: "{{ aws_credentials.db_master_username }}"
        master_password: "{{ aws_credentials.db_master_password }}"
        db_name: "trade_feed_db"
        multi_az: no
        vpc_security_group_ids:
          - sg-12345678
        db_subnet_group_name: my-subnet-group
        publicly_accessible: yes
