---
- name: Set up AWS EventBridge and SES
  hosts: localhost
  gather_facts: no

  vars:
    json_file_path: "{{ lookup('env', 'HOME') }}/trade-feed-etl-health-checker_{{ aws_region }}_{{ environment }}.json"
    aws_credentials: "{{ lookup('file', json_file_path) | from_json }}"

  tasks:
    - name: Set up AWS EventBridge rule
      aws_eventbridge_rule:
        name: "trade-feed-health-check"
        schedule_expression: "rate(15 minutes)"
        state: "ENABLED"
        description: "Trigger Lambda function every 15 minutes to check file count."
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_credentials.aws_access_key_id }}"
        aws_secret_key: "{{ aws_credentials.aws_secret_access_key }}"

    - name: Add Lambda target to the EventBridge rule
      aws_eventbridge_target:
        rule: "trade-feed-health-check"
        arn: "{{ aws_credentials.lambda_function_arn }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_credentials.aws_access_key_id }}"
        aws_secret_key: "{{ aws_credentials.aws_secret_access_key }}"

    - name: Verify an email address for SES
      aws_ses_identity:
        email: "{{ aws_credentials.ses_email }}"
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_credentials.aws_access_key_id }}"
        aws_secret_key: "{{ aws_credentials.aws_secret_access_key }}"

    - name: Create SES sending authorization policy (optional)
      aws_ses_identity_policy:
        email: "{{ aws_credentials.ses_email }}"
        policy_name: "SendEmailPolicy"
        policy:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "ses:SendEmail"
              Resource: "*"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_credentials.aws_access_key_id }}"
        aws_secret_key: "{{ aws_credentials.aws_secret_access_key }}"
